In [17]:
!pip install --upgrade scikit-learn

Requirement already satisfied: scikit-learn in ./opt/anaconda3/lib/python3.9/site-packages (1.5.1)
Requirement already satisfied: scipy>=1.6.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: numpy>=1.19.5 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.21.5)
Requirement already satisfied: joblib>=1.2.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.4.2)

In [18]:
import sklearn
print(sklearn.__version__)

1.5.1

In [19]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.experimental import enable_iterative_imputer

from sklearn.impute import IterativeImputer
import numpy as np

!pip install pandas numpy scikit-learn fancyimpute

Requirement already satisfied: pandas in ./opt/anaconda3/lib/python3.9/site-packages (1.4.2)
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.9/site-packages (1.21.5)
Requirement already satisfied: scikit-learn in ./opt/anaconda3/lib/python3.9/site-packages (1.5.1)
Requirement already satisfied: fancyimpute in ./opt/anaconda3/lib/python3.9/site-packages (0.7.0)
Requirement already satisfied: python-dateutil>=2.8.1 in ./opt/anaconda3/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./opt/anaconda3/lib/python3.9/site-packages (from pandas) (2021.3)
Requirement already satisfied: scipy>=1.6.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Requirement already satisfied: joblib>=1.2.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./opt/anaconda3/lib/python3.9/site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: knnimpute>=0.1.0 in ./opt/anaconda3/lib/python3.9/site-packages (from fancyimpute) (0.1.0)
Requirement already satisfied: cvxopt in ./opt/anaconda3/lib/python3.9/site-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: nose in ./opt/anaconda3/lib/python3.9/site-packages (from fancyimpute) (1.3.7)
Requirement already satisfied: cvxpy in ./opt/anaconda3/lib/python3.9/site-packages (from fancyimpute) (1.5.3)
Requirement already satisfied: pytest in ./opt/anaconda3/lib/python3.9/site-packages (from fancyimpute) (7.1.1)
Requirement already satisfied: six in ./opt/anaconda3/lib/python3.9/site-packages (from knnimpute>=0.1.0->fancyimpute) (1.16.0)
Requirement already satisfied: clarabel>=0.5.0 in ./opt/anaconda3/lib/python3.9/site-packages (from cvxpy->fancyimpute) (0.9.0)
Requirement already satisfied: ecos>=2 in ./opt/anaconda3/lib/python3.9/site-packages (from cvxpy->fancyimpute) (2.0.14)
Requirement already satisfied: scs>=3.2.4.post1 in ./opt/anaconda3/lib/python3.9/site-packages (from cvxpy->fancyimpute) (3.2.7)
Requirement already satisfied: osqp>=0.6.2 in ./opt/anaconda3/lib/python3.9/site-packages (from cvxpy->fancyimpute) (0.6.7.post1)
Requirement already satisfied: qdldl in ./opt/anaconda3/lib/python3.9/site-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (0.1.7.post4)
Requirement already satisfied: attrs>=19.2.0 in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (21.4.0)
Requirement already satisfied: iniconfig in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (1.1.1)
Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (1.0.0)
Requirement already satisfied: py>=1.8.2 in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (1.11.0)
Requirement already satisfied: tomli>=1.0.0 in ./opt/anaconda3/lib/python3.9/site-packages (from pytest->fancyimpute) (1.2.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./opt/anaconda3/lib/python3.9/site-packages (from packaging->pytest->fancyimpute) (3.0.4)

In [20]:
df = pd.read_csv('dataset2.csv')
df.head(16)

,TXN_DATE_TIME,TRANSACTION_ID,CUSTOMER_ID,POLICY_NUMBER,POLICY_EFF_DT,LOSS_DT,REPORT_DT,INSURANCE_TYPE,PREMIUM_AMOUNT,CLAIM_AMOUNT,...,CLAIM_STATUS,INCIDENT_SEVERITY,AUTHORITY_CONTACTED,ANY_INJURY,POLICE_REPORT_AVAILABLE,INCIDENT_STATE,INCIDENT_CITY,INCIDENT_HOUR_OF_THE_DAY,AGENT_ID,VENDOR_ID
0,2020-06-01 00:00:00,TXN00000001,A00003822,PLC00008468,2015-06-23,2020-05-16,2020-05-21,Health,157.13,9000,...,A,Major Loss,Police,0,1,GA,Savannah,4,AGENT00413,VNDR00556
1,2020-06-01 00:00:00,TXN00000002,A00008149,PLC00009594,2018-04-21,2020-05-13,2020-05-18,Property,141.71,26000,...,A,Total Loss,Ambulance,1,0,AL,Montgomery,0,AGENT00769,VNDR00592
2,2020-06-01 00:00:00,TXN00000003,A00003172,PLC00007969,2019-10-03,2020-05-21,2020-05-26,Property,157.24,13000,...,A,Total Loss,Police,0,1,CO,Grand Junction,19,AGENT00883,VNDR00031
3,2020-06-01 00:00:00,TXN00000004,A00007572,PLC00009292,2016-11-29,2020-05-14,2020-05-19,Health,172.87,16000,...,A,Minor Loss,Ambulance,0,0,GA,Savannah,12,AGENT00278,VNDR00075
4,2020-06-01 00:00:00,TXN00000005,A00008173,PLC00000204,2011-12-26,2020-05-17,2020-05-22,Travel,88.53,3000,...,A,Major Loss,Police,0,1,TN,Nashville,18,AGENT00636,VNDR00472
5,2020-06-01 00:00:00,TXN00000006,A00003571,PLC00007244,2012-12-28,2020-05-20,2020-05-25,Life,87.02,63000,...,A,Major Loss,Ambulance,0,1,AZ,Glendale,0,AGENT00402,NaN
6,2020-06-01 00:00:00,TXN00000007,A00007245,PLC00002796,2012-10-26,2020-05-13,2020-05-18,Health,197.23,3000,...,A,Major Loss,Police,1,1,CT,Manchester,10,AGENT00322,VNDR00150
7,2020-06-01 00:00:00,TXN00000008,A00004301,PLC00002925,2018-12-30,2020-05-14,2020-05-19,Motor,83.77,8000,...,A,Total Loss,Police,0,1,FL,Panama City Beach,10,AGENT00152,VNDR00326
8,2020-06-01 00:00:00,TXN00000009,A00004671,PLC00006886,2019-06-27,2020-05-21,2020-05-26,Motor,82.14,5000,...,A,Major Loss,Police,0,1,AZ,Glendale,22,AGENT00450,VNDR00437
9,2020-06-01 00:00:00,TXN00000010,A00002020,PLC00007657,2015-12-19,2020-05-15,2020-05-20,Travel,71.29,4000,...,A,Major Loss,None,0,0,CA,San Leandro,4,AGENT00682,NaN
10,2020-06-01 00:00:00,TXN00000011,A00007952,PLC00003007,2019-03-30,2020-05-20,2020-05-25,Life,61.45,92000,...,A,Major Loss,Ambulance,1,1,MD,Crofton,23,AGENT01091,VNDR00163
11,2020-06-01 00:00:00,TXN00000012,A00006313,PLC00002139,2016-07-22,2020-05-21,2020-05-26,Motor,101.15,8000,...,D,Major Loss,Ambulance,1,1,CT,Manchester,3,AGENT00288,NaN
12,2020-06-01 00:00:00,TXN00000013,A00003693,PLC00007839,2019-06-12,2020-05-24,2020-05-27,Health,157.95,11000,...,A,Major Loss,None,0,1,KY,Louisville,22,AGENT00015,VNDR00191
13,2020-06-01 00:00:00,TXN00000014,A00007988,PLC00002521,2020-01-29,2020-05-18,2020-05-23,Life,64.16,51000,...,A,Total Loss,Ambulance,1,0,AK,Anchorage,0,AGENT01094,NaN
14,2020-06-01 00:00:00,TXN00000015,A00005617,PLC00007011,2015-06-08,2020-05-20,2020-05-25,Mobile,6.76,700,...,A,Major Loss,Police,1,1,CO,Arvada,11,AGENT00324,VNDR00135
15,2020-06-01 00:00:00,TXN00000016,A00008033,PLC00008152,2011-01-25,2020-05-12,2020-05-17,Motor,128.73,9000,...,A,Minor Loss,Police,0,1,AR,Fayetteville,22,AGENT00608,VNDR00051

In [21]:
# Check for missing values in each column
missing_values = df.isna().sum()

# Print columns with missing values
print("Columns with missing values:")
print(missing_values[missing_values > 0])

Columns with missing values:
ADDRESS_LINE2               8505
CITY                          54
CUSTOMER_EDUCATION_LEVEL     529
INCIDENT_CITY                 46
VENDOR_ID                   3245
dtype: int64

In [22]:
# Initialize LabelEncoder
le = LabelEncoder()

# Encode the 'CUSTOMER_EDUCATION_LEVEL' column
df['CUSTOMER_EDUCATION_LEVEL'] = le.fit_transform(df['CUSTOMER_EDUCATION_LEVEL'].astype(str))

In [23]:
# Initialize IterativeImputer with RandomForestClassifier
imputer = IterativeImputer(estimator=RandomForestClassifier(n_estimators=100, random_state=0), random_state=0)

In [24]:
# Reshape the data to ensure it is in the correct format
df_imputed = df.copy()
df_imputed[['CUSTOMER_EDUCATION_LEVEL']] = imputer.fit_transform(df[['CUSTOMER_EDUCATION_LEVEL']])

In [25]:
# Decode the 'CUSTOMER_EDUCATION_LEVEL' column
df_imputed['CUSTOMER_EDUCATION_LEVEL'] = le.inverse_transform(df_imputed['CUSTOMER_EDUCATION_LEVEL'].astype(int))

In [26]:
print(df_imputed[['CUSTOMER_EDUCATION_LEVEL']].head())

  CUSTOMER_EDUCATION_LEVEL
0                 Bachelor
1                 Bachelor
2                      PhD
3                  Masters
4                  Masters

In [27]:
# Save the imputed dataset
df_imputed.to_csv('imputed_dataset.csv', index=False)

In [28]:
missing_values = df.isna().sum()
print(missing_values)

TXN_DATE_TIME                  0
TRANSACTION_ID                 0
CUSTOMER_ID                    0
POLICY_NUMBER                  0
POLICY_EFF_DT                  0
LOSS_DT                        0
REPORT_DT                      0
INSURANCE_TYPE                 0
PREMIUM_AMOUNT                 0
CLAIM_AMOUNT                   0
CUSTOMER_NAME                  0
ADDRESS_LINE1                  0
ADDRESS_LINE2               8505
CITY                          54
STATE                          0
POSTAL_CODE                    0
SSN                            0
MARITAL_STATUS                 0
AGE                            0
TENURE                         0
EMPLOYMENT_STATUS              0
NO_OF_FAMILY_MEMBERS           0
RISK_SEGMENTATION              0
HOUSE_TYPE                     0
SOCIAL_CLASS                   0
ROUTING_NUMBER                 0
ACCT_NUMBER                    0
CUSTOMER_EDUCATION_LEVEL       0
CLAIM_STATUS                   0
INCIDENT_SEVERITY              0
AUTHORITY_CONTACTED            0
ANY_INJURY                     0
POLICE_REPORT_AVAILABLE        0
INCIDENT_STATE                 0
INCIDENT_CITY                 46
INCIDENT_HOUR_OF_THE_DAY       0
AGENT_ID                       0
VENDOR_ID                   3245
dtype: int64

In [31]:
# Check for missing values in each column
missing_values = df.isna().sum()

# Print columns with missing values
print("Columns with missing values:")
print(missing_values[missing_values > 0])

Columns with missing values:
ADDRESS_LINE2    8505
CITY               54
INCIDENT_CITY      46
VENDOR_ID        3245
dtype: int64